### ISSUE TITLE
.samp + .info

### ISSUE THREAD

**Issue by Roma-Skull** [Nisto/musyx-extract#2] opened 2018-06-13 20:48 UTC
Hello. I'm trying unpack music data for game "Skies of Arcadia". In "sound" folders contains .info and .samp files, but script want to .sdir files...

How to extract files correctly?

In attach samples of this files. 

Thank you.

[sound.zip](https://github.com/Nisto/musyx-extract/files/2099837/sound.zip)

**Comment by Nisto** [comment] 2018-07-15 20:31
@Black-millenium Hi. Sorry for the late response. I don't recall seeing the Issue in my feed! Nevertheless, I took a look at the files and managed to figure it out, so I've put together a script for the .info files. Seems to play fine with [amuse](https://github.com/AxioDL/amuse), but let me know if you have any problems!

https://github.com/Nisto/extractors/blob/master/skies_of_arcadia_info.py

**Comment by GunnaGitGud95** [comment] 2020-05-13 14:02
Im using the script to extract PKM Colo .samp file(no .
[snd_musicsamp.zip](https://github.com/Nisto/musyx-extract/files/4622354/snd_musicsamp.zip)

sdir file in the game) but the script just always shutdown after a sec whatever normal open or drag the file to it. What do i do?

**Comment by Nisto** [comment] 2020-05-13 16:37
@GunnaGitGud95 There is always .sdir data in some form in MusyX games, at least for GameCube music projects, and I know someone has already used my script in the past to extract Pokemon Colosseum. So give another look for the respective needed files, and make sure you use `MusyXExtract.py`, NOT `skies_of_arcadia_info.py`, if that's what you've been trying.

**Comment by GunnaGitGud95** [comment] 2020-05-14 03:04
> @GunnaGitGud95 There is always .sdir data in some form in MusyX games, at least for GameCube music projects, and I know someone has already used my script in the past to extract Pokemon Colosseum. So give another look for the respective needed files, and make sure you use `MusyXExtract.py`, NOT `skies_of_arcadia_info.py`, if that's what you've been trying.

I am using MusyXExtract of course, i use gc rebuild to extract game dump, bunch of fsys, some bin, samp and thp but no sdir, im stuck, can u point me out where the file is, im no expert for this.

**Comment by Nisto** [comment] 2020-05-21 20:10
@GunnaGitGud95 

1. Extract the file `common.fsys` from the game disc

2. Extract the contents of `common.fsys` using the [QuickBMS](https://aluigi.altervista.org/quickbms.htm) script linked in [this article](
https://projectpokemon.org/tutorials/rom/stars-pok%C3%A9mon-colosseum-and-xd-hacking-tutorial/part-1-file-decompression-and-recompression-r5/)

3. Rename the extracted `*_sdir.fdat`, `*_pool.fdat`, `*_proj.fdat` files to `*.sdir`, `*.pool`, `*.proj` respectively and put these into a folder together with the `*.samp` files you already have

4. Pass the folder to `MusyXExtract.py`


Please mention me (@Nisto) if this helps so I can close this issue.

**Comment by GunnaGitGud95** [comment] 2020-05-22 03:40
> @GunnaGitGud95
> 
> 1. Extract the file `common.fsys` from the game disc
> 2. Extract the contents of `common.fsys` using the [QuickBMS](https://aluigi.altervista.org/quickbms.htm) script linked in [this article](https://projectpokemon.org/tutorials/rom/stars-pok%C3%A9mon-colosseum-and-xd-hacking-tutorial/part-1-file-decompression-and-recompression-r5/)
> 3. Rename the extracted `*_sdir.fdat`, `*_pool.fdat`, `*_proj.fdat` files to `*.sdir`, `*.pool`, `*.proj` respectively and put these into a folder together with the `*.samp` files you already have
> 4. Pass the folder to `MusyXExtract.py`
> 
> Please mention me (@Nisto) if this helps so I can close this issue.

**Comment by GunnaGitGud95** [comment] 2020-05-22 03:59
> > @GunnaGitGud95
> > 
> > 1. Extract the file `common.fsys` from the game disc
> > 2. Extract the contents of `common.fsys` using the [QuickBMS](https://aluigi.altervista.org/quickbms.htm) script linked in [this article](https://projectpokemon.org/tutorials/rom/stars-pok%C3%A9mon-colosseum-and-xd-hacking-tutorial/part-1-file-decompression-and-recompression-r5/)
> > 3. Rename the extracted `*_sdir.fdat`, `*_pool.fdat`, `*_proj.fdat` files to `*.sdir`, `*.pool`, `*.proj` respectively and put these into a folder together with the `*.samp` files you already have
> > 4. Pass the folder to `MusyXExtract.py`
> > 
> > Please mention me (@Nisto) if this helps so I can close this issue.

(@Nisto) In the time waiting ur response i already extract the file but not what i want, so i extract bgmarchive.fsys, the file full unsuable or maybe .song. I want to mod the music but now im stuck again, i also use amuse, try to play files but no good.

**Comment by Nisto** [comment] 2020-05-22 06:49
That's a different matter to which I can't respond.

**Closed as completed by Nisto** 2020-05-22 06:49 UTC

**Comment by HeyItsShay** [comment] 2021-11-29 05:08
@Nisto Sorry to revive a closed issue thread, but I'm having trouble figuring out this same issue.

I extracted all the files from the Skies of Arcadia ISO. There is a folder labeled "sounds" which contains files with extensions `.dsp` `.info` and `.samp`. The `.dsp` files I am able to convert to `.wav` using VGMStream. The remaining files are paired info+samp files of the same name as shown by the initial post's `sound.zip`. I tried running your `skies_of_arcadia_info.py` script and your `MusyXExtract.py` script in order to convert the paired info+samp files into `.dsp` files, but neither script would convert any files.

The exact thing I'm trying to do is convert the folder full of `.info` and `.samp` files into a usable file format like `.dsp` so I can then convert them into `.wav` using VGMStream. Any info or guidance would be extremely appreciated, thanks in advance!

**Comment by Nisto** [comment] 2021-11-29 17:55
@HeyItsShay Are you supplying proper arguments to the scripts? For `skies_of_arcadia_info.py` you must supply a **single `.info` file**. For `MusyXExtract.py` you must supply a **directory** containing `.sdir` and `.samp` files.

Generally speaking, to supply file/folder arguments to scripts, it is usually enough to simply drag them and drop them on a script. But if your environment doesn't have support for drag-n-drop, you have to supply them via command-line. E.g.:

* `"X:\skies_of_arcadia_info.py" "X:\Skies of Arcadia\my folder containing info files\abcxyz.info"`
* `"X:\MusyXExtract.py" "X:\Skies of Arcadia\my folder containing sdir and samp files"`

**Comment by HeyItsShay** [comment] 2021-11-29 21:44
@Nisto Okay so I see the problem is that I was running my .py scripts through PyCharm for another project and that doesn't allow the drag and drop method of running scripts on specific files, at least with my configuration. Changing the .py extension to run via Python Console lets me drag and drop the `.info` files onto `skies_of_arcadia_info.py` and convert them just fine, and from there I can drag the entire folder containing the converted `.info` and `.samp` files onto `MusyXExtract.py` to do a batch conversion into `.dsp`. Everything works, thanks for the help!

I don't suppose there's a way to do a batch conversion of these `.info` files? I don't mind doing them individually, but there are nearly 600 of them for Skies of Arcadia.

Edit: I ended up converting the files one by one, it didn't take too long! Thanks a ton for your help, Nisto!
